trainer:
  model:
    name: unet_3d
    feture_map: [64, 128, 256, 512]
    channels: [0, 1, 2]

  optim:
    name: adam
    lr : 0.01

  loss: DiceLoss
  metrics: [accuracy, ]

  epochs: 50

  train_ds:
    path: ../data/gbm_train_ds/
    batch_size: 4
    sample_dimension: [12, 256, 256]
    pixel_stride: [1, 16, 16]
    pin_memory: False
    shuffle: False

  valid_ds:
    path: ../data/gbm_valid_ds/
    batch_size: 4
    sample_dimension: [12, 256, 256]
    pixel_stride: [1, 16, 16]
    pin_memory: False
    shuffle: True
    batch_limit: 300

  visualization: True
  visualization_path: /tmp/gbm-vv/

  device: gpu
  mixed_precision: False

  ddp: True

logging:
  log_level: INFO
  log_file: train.log
  log_std: False
  tqdm: True

