trainer:
  model:
    name: unet_3d
    tag: adam_dice_128_256_512_1024
    feature_maps: [128, 256, 512, 1024]
    channels: [0, 2]

  optim:
    name: adam
    lr : 0.01

  loss: DiceLoss
  metrics: [accuracy, ]
  report_freq: 10

  epochs: 200
  save_interval: 5
  snapshot_path: snapshots/unet3d.pt

  train_ds:
    path: ../data/gbm_train_ds/
    batch_size: 3
    sample_dimension: [12, 256, 256]
    pixel_stride: [1, 16, 16]
    pin_memory: False
    shuffle: False

  valid_ds:
    path: ../data/gbm_valid_ds/
    batch_size: 3
    sample_dimension: [12, 256, 256]
    pixel_stride: [1, 16, 16]
    pin_memory: False
    shuffle: False

  visualization:
    enabled: True
    chance: 0.2
    path: gbm-vv/
    gif: True
    tif: False
    mesh: False

  tensorboard:
    enabled: True
    path: tensorboard/
    metrics: True

  device: cuda
  mixed_precision: True

  ddp:
    enabled: True
    no_of_nodes: 5
    rdzv_backend: c10d
    rdzv_endpoint: 192.168.227.236:29603 

logging:
  log_level: INFO
  log_file: logs/train.log
  log_std: True

