trainer:
  model:
    # unet_3d, undet_3d_me
    name: unet_3d
    # Used for result dir and snapshot names
    tag: adam_dice_big
    # Huge: [128, 256, 512, 1024]
    # Big: [64, 128, 256, 512]
    # Medium: [64, 128, 256]
    # Small: [32, 64, 128]
    # Tiny: [32, 64]
    feature_maps: [64, 128, 256, 512]
    # 0: Nephrin
    # 1: WGA
    # 2: Collagen4
    channels: [0, 1, 3]

  optim:
    name: adam
    lr : 0.01

  loss: DiceLoss
  metrics: [accuracy, ]
  # Every report_freq batch, metrics and losses will be logged
  report_freq: 10

  epochs: 50
  # Every save_interval a snapshot will be created
  save_interval: 5
  snapshot_path: snapshots/

  train_ds:
    path: ../data/gbm_train_ds/
    batch_size: 6
    sample_dimension: [12, 256, 256]
    pixel_stride: [1, 16, 16]
    pin_memory: True
    # shuffle should be off when using DDP
    shuffle: False

  valid_ds:
    path: ../data/gbm_valid_ds/
    batch_size: 6
    sample_dimension: [12, 256, 256]
    pixel_stride: [1, 16, 16]
    pin_memory: True
    # shuffle should be off when using DDP
    shuffle: False

  visualization:
    enabled: True
    # The chance for a batch to create visualization
    chance: 0.2
    path: gbm-vv/
    gif: True
    tif: False
    mesh: False

  tensorboard:
    enabled: True
    path: tensorboard/
    metrics: True

  device: cuda
  mixed_precision: True

  ddp:
    enabled: True
    no_of_nodes: 3
    rdzv_backend: c10d
    rdzv_endpoint: 192.168.227.235:29603

logging:
  log_level: INFO
  log_file: logs/train.log
  log_std: True

